#ifndef TYPEDEFS_ENGINE_H
#define TYPEDEFS_ENGINE_H

// toggle debug functionality (DebugShapes and DebugMenu)
#define ENGINE_DEBUG_

typedef unsigned int uint;
#define BUFFER_OFFSET(i) ((char *)NULL + (i))

#pragma region Renderer
	#define GEOMETRIES_MAX_CAPACITY 64
	#define BUFFEREDGEOMETRIES_MAX_CAPACITY 32
	#define SHADERPROGRAMS_MAX_CAPACITY 10
	#define RENDERABLES_MAX_CAPACITY 128

	#define BUFFER_SIZE 0x100000
	#define VERTEXBUFFERIDS_MAX_CAPACITY 32
	#define INDEXBUFFERIDS_MAX_CAPACITY 8
	#define UNIFORMBUFFERIDS_MAX_CAPACITY 8
	#define UNIFORMNAME_MAX_CAPACITY 48
	#define UNIFORMDATA_MAX_CAPACITY 64
	#define TEXTURES_MAX_CAPACITY 16

	#define ATTRIBS_MAX_CAPACITY 8

	#define UNIFORMS_MAX_CAPACITY 16
	#define TEXTUREINFOS_MAX_CAPACITY 32
	#define UNIFORMBLOCKS_MAX_CAPACITY 8
	#define BUFFEREDGEOMETRY_MAX_ATTRIBS 8
#pragma endregion

#endif